version: '3.9'

services:
  paresr:
      container_name: parser
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - ./.env
      depends_on:
       - db
      restart: always
      ports: 
        - "8001:8000"
  db:
    image: "postgres:15.2"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql/data:/var/lib/postgresql/data
    